"""Business logic for private file storage and per-file access checks."""

from __future__ import annotations

import os
import re
import stat
from pathlib import Path
from typing import BinaryIO
from uuid import uuid4

from flask import current_app
from sqlalchemy import func, or_, select
from werkzeug.datastructures import FileStorage
from werkzeug.utils import secure_filename

from app.extensions import db
from app.models.file import FileRecord
from app.models.permission import FilePermission


_OPAQUE_FILENAME_PATTERN = re.compile(r"\A[0-9a-f]{32}\Z")
_COPY_CHUNK_SIZE = 64 * 1024
_DEFAULT_MAX_FILE_SIZE = 16 * 1024 * 1024


class FileServiceError(Exception):
    """A file operation failure that is safe to report to an API client."""

    status_code = 400
    message = "The file operation could not be completed."

    def __init__(self, message: str | None = None) -> None:
        super().__init__(message or self.message)
        self.public_message = message or self.message


class InvalidUploadError(FileServiceError):
    status_code = 400
    message = "A valid file is required."


class FileTooLargeError(FileServiceError):
    status_code = 413
    message = "The uploaded file is too large."


class FileRecordNotFoundError(FileServiceError):
    status_code = 404
    message = "File not found."


class FileAccessDeniedError(FileServiceError):
    status_code = 403
    message = "You are not authorized to access this file."


class FileDownloadDeniedError(FileAccessDeniedError):
    message = "You are not authorized to download this file."


class FileOwnerRequiredError(FileAccessDeniedError):
    message = "Only the file owner can perform this action."


class StoredFileUnavailableError(FileServiceError):
    status_code = 404
    message = "File is unavailable."


def _storage_root() -> Path:
    """Resolve the configured, non-public storage directory."""

    configured_path = current_app.config.get("UPLOAD_FOLDER")
    if not configured_path:
        raise RuntimeError("UPLOAD_FOLDER must be configured.")

    root = Path(configured_path).expanduser()
    if not root.is_absolute():
        root = Path(current_app.root_path).parent / root
    root = root.resolve()

    # Flask only exposes its static directory automatically. Refuse a storage
    # configuration below it so a deployment mistake cannot bypass the API.
    if current_app.static_folder:
        static_root = Path(current_app.static_folder).resolve()
        try:
            root.relative_to(static_root)
        except ValueError:
            pass
        else:
            raise RuntimeError("UPLOAD_FOLDER cannot be inside the static directory.")

    root.mkdir(mode=0o700, parents=True, exist_ok=True)
    return root


def _storage_path(stored_filename: str) -> Path:
    """Build a contained path for an opaque filename generated by this app."""

    if not _OPAQUE_FILENAME_PATTERN.fullmatch(stored_filename):
        raise StoredFileUnavailableError()

    root = _storage_root()
    candidate = root / stored_filename
    resolved = candidate.resolve(strict=False)
    try:
        resolved.relative_to(root)
    except ValueError as exc:
        raise StoredFileUnavailableError() from exc

    # Generated files are regular files. Never follow a storage-entry symlink,
    # even when its eventual target happens to remain under the upload root.
    if candidate.is_symlink():
        raise StoredFileUnavailableError()
    return resolved


def _maximum_file_size() -> int:
    configured_size = current_app.config.get("MAX_FILE_SIZE")
    if configured_size is None:
        configured_size = current_app.config.get("MAX_CONTENT_LENGTH")
    if configured_size is None:
        configured_size = _DEFAULT_MAX_FILE_SIZE
    try:
        maximum = int(configured_size)
    except (TypeError, ValueError) as exc:
        raise RuntimeError("MAX_FILE_SIZE must be a positive integer.") from exc
    if maximum <= 0:
        raise RuntimeError("MAX_FILE_SIZE must be a positive integer.")
    return maximum


def _validated_original_filename(upload: FileStorage | None) -> str:
    if upload is None or not isinstance(upload.filename, str):
        raise InvalidUploadError()

    filename = upload.filename.strip()
    if not filename or len(filename) > 255:
        raise InvalidUploadError("The filename is invalid.")
    if filename in {".", ".."} or "/" in filename or "\\" in filename:
        raise InvalidUploadError("The filename is invalid.")
    if any(ord(character) < 32 or ord(character) == 127 for character in filename):
        raise InvalidUploadError("The filename is invalid.")

    # secure_filename is deliberately used only as a validation aid. The
    # normalized result is never used as a path, and the original safe basename
    # is retained for display and Content-Disposition.
    if not secure_filename(filename):
        raise InvalidUploadError("The filename is invalid.")
    return filename


def _copy_with_limit(
    source: BinaryIO,
    destination: Path,
    maximum_size: int,
) -> int:
    """Copy an upload to a newly-created private file and return its size."""

    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    descriptor = os.open(destination, flags, 0o600)
    complete = False
    size = 0
    try:
        with os.fdopen(descriptor, "wb") as stored_file:
            while True:
                chunk = source.read(_COPY_CHUNK_SIZE)
                if not chunk:
                    break
                size += len(chunk)
                if size > maximum_size:
                    raise FileTooLargeError()
                stored_file.write(chunk)
        complete = True
        return size
    finally:
        if not complete:
            destination.unlink(missing_ok=True)


def _write_upload(upload: FileStorage) -> tuple[str, Path, int]:
    maximum_size = _maximum_file_size()

    # O_EXCL handles the practically impossible UUID collision without ever
    # overwriting an existing private file.
    for _ in range(5):
        stored_filename = uuid4().hex
        destination = _storage_path(stored_filename)
        try:
            size = _copy_with_limit(upload.stream, destination, maximum_size)
        except FileExistsError:
            continue
        return stored_filename, destination, size
    raise RuntimeError("Could not allocate a unique storage filename.")


def upload_file(upload: FileStorage | None, owner: object) -> FileRecord:
    """Persist an uploaded file and its metadata for the authenticated owner."""

    original_filename = _validated_original_filename(upload)
    assert upload is not None  # nosec B101
    stored_filename, stored_path, file_size = _write_upload(upload)

    record = FileRecord(
        original_filename=original_filename,
        stored_filename=stored_filename,
        owner_id=owner.id,
        file_size=file_size,
    )
    try:
        db.session.add(record)
        db.session.commit()
    except Exception:
        db.session.rollback()
        stored_path.unlink(missing_ok=True)
        raise
    return record


def get_file(file_id: str) -> FileRecord:
    record = db.session.get(FileRecord, file_id)
    if record is None:
        raise FileRecordNotFoundError()
    return record


def user_can_access(record: FileRecord, user_id: int) -> bool:
    if record.owner_id == user_id:
        return True
    permission = db.session.execute(
        select(FilePermission.id)
        .where(
            FilePermission.file_id == record.id,
            FilePermission.user_id == user_id,
        )
    ).scalar_one_or_none()
    return permission is not None


def get_accessible_file(
    file_id: str,
    user_id: int,
    *,
    for_download: bool = False,
) -> FileRecord:
    record = get_file(file_id)
    if not user_can_access(record, user_id):
        if for_download:
            raise FileDownloadDeniedError()
        # Metadata lookups deliberately hide whether an inaccessible UUID exists.
        raise FileRecordNotFoundError()
    return record


def get_owned_file(file_id: str, owner_id: int) -> FileRecord:
    record = get_file(file_id)
    if record.owner_id != owner_id:
        raise FileOwnerRequiredError()
    return record


def list_accessible_files(user_id: int) -> list[FileRecord]:
    permission_exists = (
        select(FilePermission.id)
        .where(
            FilePermission.file_id == FileRecord.id,
            FilePermission.user_id == user_id,
        )
        .exists()
    )
    statement = (
        select(FileRecord)
        .where(
            or_(
                FileRecord.owner_id == user_id,
                permission_exists,
            )
        )
        .order_by(FileRecord.created_at.desc(), FileRecord.id)
    )
    return list(db.session.execute(statement).scalars().all())


def list_accessible_file_summaries(user_id: int) -> list[dict[str, object]]:
    """Return safe dashboard metadata derived from backend access records.

    ``access_type`` is presentation data, not an authorization credential. All
    subsequent operations still execute their normal service-layer checks.
    """

    records = list_accessible_files(user_id)
    owned_ids = [record.id for record in records if record.owner_id == user_id]
    permission_counts: dict[str, int] = {}
    if owned_ids:
        count_statement = (
            select(FilePermission.file_id, func.count(FilePermission.id))
            .where(FilePermission.file_id.in_(owned_ids))
            .group_by(FilePermission.file_id)
        )
        permission_counts = {
            file_id: int(count)
            for file_id, count in db.session.execute(count_statement).all()
        }

    summaries: list[dict[str, object]] = []
    for record in records:
        summary = record.to_dict()
        is_owner = record.owner_id == user_id
        summary["access_type"] = "owner" if is_owner else "shared"
        summary["owner"] = {
            "id": record.owner.id,
            "username": record.owner.username,
        }
        if is_owner:
            summary["authorized_user_count"] = permission_counts.get(record.id, 0)
        summaries.append(summary)
    return summaries


def _open_stored_file(record: FileRecord) -> BinaryIO:
    """Open a validated regular file without following a final symlink."""

    stored_path = _storage_path(record.stored_filename)
    flags = os.O_RDONLY
    if hasattr(os, "O_CLOEXEC"):
        flags |= os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW

    try:
        descriptor = os.open(stored_path, flags)
    except OSError as exc:
        raise StoredFileUnavailableError() from exc

    try:
        file_status = os.fstat(descriptor)
        if not stat.S_ISREG(file_status.st_mode):
            raise StoredFileUnavailableError()
        if file_status.st_size != record.file_size:
            raise StoredFileUnavailableError()
        return os.fdopen(descriptor, "rb")
    except Exception:
        os.close(descriptor)
        raise


def get_download(file_id: str, user_id: int) -> tuple[FileRecord, BinaryIO]:
    """Authorize a download, then return an already-validated open file."""

    record = get_accessible_file(file_id, user_id, for_download=True)
    stored_file = _open_stored_file(record)
    return record, stored_file


def delete_file(file_id: str, owner_id: int) -> FileRecord:
    """Delete a file and its permission records; only its owner may do so."""

    record = get_owned_file(file_id, owner_id)
    stored_path = _storage_path(record.stored_filename)

    # Delete the bytes before metadata so a successful API response never leaves
    # the supposedly deleted content downloadable through this application.
    stored_path.unlink(missing_ok=True)

    try:
        db.session.query(FilePermission).filter_by(file_id=record.id).delete(
            synchronize_session=False
        )
        db.session.delete(record)
        db.session.commit()
    except Exception:
        db.session.rollback()
        raise
    return record
